spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages
  servlet:
    multipart:
      location: C:\Users\LENOVO\IdeaProjects\MyProjects\HotelBooking\images