spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: C:\Users\LENOVO\IdeaProjects\MyProjects\HotelBooking\images
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1084978167683-4j6uftqv8lhdhmdcnf8ina0dgeruj13j.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://localhost:8080/login/oauth2/code/google
server:
  tomcat:
    max-swallow-size: -1
my-app:
  content:
    no-image-available: NoImageAvailable.jpg
