spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
  messages:
    basename: messages
  servlet:
    multipart:
      location: C:\Users\LENOVO\IdeaProjects\MyProjects\HotelBooking\images